# Generated by Django 4.1.6 on 2023-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('codigo', models.IntegerField(unique=True)),
                ('memoria', models.CharField(max_length=50)),
                ('camara', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('bateria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
    ]
